// Mapeamento completo e testado de capas reais de todos os 91 livros do catálogo
export const bookCoversMap = {
  "Se Não Fosse Você": "https://m.media-amazon.com/images/I/91UJSr2IukL._AC_UL800_QL65_.jpg",
  "Amor por Acaso": "https://m.media-amazon.com/images/I/61t4VlpXoOL._AC_UL800_QL65_.jpg",
  "Sem Esperança": "https://m.media-amazon.com/images/I/91DszGVK+2L._AC_UL800_QL65_.jpg",
  "Talvez Agora": "https://m.media-amazon.com/images/I/81GH54cTScL._AC_UL800_QL65_.jpg",
  "Talvez Um Dia": "https://m.media-amazon.com/images/I/815OsC8zbwL._AC_UL800_QL65_.jpg",
  "Layla": "https://m.media-amazon.com/images/I/91-M+6ZOjuL._AC_UL800_QL65_.jpg",
  "Lembranças d'Ele": "https://m.media-amazon.com/images/I/81tvgUwzabL._AC_UL800_QL65_.jpg",
  "A Exceção à Regra": "https://m.media-amazon.com/images/I/71MUhPEx9-L._AC_UL800_QL65_.jpg",
  "Até o Verão Terminar": "https://m.media-amazon.com/images/I/81u8c5lziEL._AC_UL800_QL65_.jpg",
  "Confesse": "https://m.media-amazon.com/images/I/91JhEqiauUL._AC_UL800_QL65_.jpg",
  "É Assim que Acaba": "https://m.media-amazon.com/images/I/71sdFEHoRGL._AC_UL800_QL65_.jpg",
  "É Assim que Começa": "https://m.media-amazon.com/images/I/81Izv2GRWoL._AC_UL800_QL65_.jpg",
  "Novembro, 9": "https://m.media-amazon.com/images/I/917G-FdK2kL._AC_UL800_QL65_.jpg",
  "O Lado Feio do Amor": "https://m.media-amazon.com/images/I/81FEytag46L._AC_UL800_QL65_.jpg",
  "Todas as Suas (Im)Perfeições": "https://m.media-amazon.com/images/I/81tZj9h9PAL._AC_UL800_QL65_.jpg",
  "Uma Segunda Chance": "https://m.media-amazon.com/images/I/813WvRoZ0HL._AC_UL800_QL65_.jpg",
  "Verity": "https://m.media-amazon.com/images/I/91SDZ2eUj+L._AC_UL800_QL65_.jpg",
  "Apostando no Amor": "https://m.media-amazon.com/images/I/61qs2JCP4NL._AC_UL800_QL65_.jpg",
  "Melhor do que nos Filmes": "https://m.media-amazon.com/images/I/61y5iLUKS3L._AC_UL800_QL65_.jpg",
  "Mr. Wrong Number": "https://m.media-amazon.com/images/I/81tbn9DicaL._AC_UL800_QL65_.jpg",
  "Nada Como nos Filmes": "https://m.media-amazon.com/images/I/71E7CFZbWyL._AC_UL800_QL65_.jpg",
  "The Do-Over": "https://m.media-amazon.com/images/I/71g-+Mn7zQL._AC_UL800_QL65_.jpg",
  "The Love Wager": "https://m.media-amazon.com/images/I/71r+niNLzDL._AC_UL800_QL65_.jpg",
  "A Hipótese do Amor": "https://m.media-amazon.com/images/I/81LTEfXYgcL._AC_UL800_QL65_.jpg",
  "A Razão do Amor": "https://m.media-amazon.com/images/I/81bkmJnflPL._AC_UL800_QL65_.jpg",
  "A Teoria da Conquista": "https://m.media-amazon.com/images/I/71dFi0nYJFL._AC_UL800_QL65_.jpg",
  "Noiva": "https://m.media-amazon.com/images/I/812RDxFDd8L._AC_UL800_QL65_.jpg",
  "Not in Love": "https://m.media-amazon.com/images/I/71i-HM1ZrlL._AC_UL800_QL65_.jpg",
  "Xeque-Mate": "https://m.media-amazon.com/images/I/81O6eWVPaiL._AC_UL800_QL65_.jpg",
  "As Mil Partes do Meu Coração": "https://m.media-amazon.com/images/I/814pUv-EGbL._AC_UL800_QL65_.jpg",
  "Loucos por Livros": "https://m.media-amazon.com/images/I/718y6CqQ9KL._AC_UL800_QL65_.jpg",
  "De Férias com Você": "https://m.media-amazon.com/images/I/81xU-Ue9uXL._AC_UL800_QL65_.jpg",
  "Leitura de Verão": "https://m.media-amazon.com/images/I/81r1j1NnZLL._AC_UL800_QL65_.jpg",
  "Lugar Feliz": "https://m.media-amazon.com/images/I/81l80YcE-ZL._AC_UL800_QL65_.jpg",
  "Nem Te Conto": "https://m.media-amazon.com/images/I/71G1mYk7SjL._AC_UL800_QL65_.jpg",
  "Os Sete Maridos de Evelyn Hugo": "https://m.media-amazon.com/images/I/81r52N2H9cL._AC_UL800_QL65_.jpg",
  "Daisy Jones & The Six": "https://m.media-amazon.com/images/I/81B+G7x4KOL._AC_UL800_QL65_.jpg",
  "Malibu Renasce": "https://m.media-amazon.com/images/I/81k3f0e8fYL._AC_UL800_QL65_.jpg",
  "Carrie Soto Está de Volta": "https://m.media-amazon.com/images/I/81gR0XW1aNL._AC_UL800_QL65_.jpg",
  "Em Outra Vida, Talvez?": "https://m.media-amazon.com/images/I/81Lg7Y9mU3L._AC_UL800_QL65_.jpg",
  "Amor(es) Verdadeiro(s)": "https://m.media-amazon.com/images/I/81i-Z718vIL._AC_UL800_QL65_.jpg",
  "Corte de Espinhos e Rosas": "https://m.media-amazon.com/images/I/81s042Ff8hL._AC_UL800_QL65_.jpg",
  "Corte de Névoa e Fúria": "https://m.media-amazon.com/images/I/81Ksc0-j7tL._AC_UL800_QL65_.jpg",
  "Corte de Asas e Ruína": "https://m.media-amazon.com/images/I/81R56yH8JNL._AC_UL800_QL65_.jpg",
  "Corte de Chamas Prateadas": "https://m.media-amazon.com/images/I/81Z3aR32F0L._AC_UL800_QL65_.jpg",
  "Casa de Terra e Sangue": "https://m.media-amazon.com/images/I/81gL+l5q2NL._AC_UL800_QL65_.jpg",
  "Trono de Vidro": "https://m.media-amazon.com/images/I/81K09F+jP2L._AC_UL800_QL65_.jpg",
  "Quarta Asa": "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UL800_QL65_.jpg",
  "Chama de Ferro": "https://m.media-amazon.com/images/I/81G3B5T4YhL._AC_UL800_QL65_.jpg",
  "A Última Carta": "https://m.media-amazon.com/images/I/81h2N3zVpYL._AC_UL800_QL65_.jpg",
  "Vermelho, Branco e Sangue Azul": "https://m.media-amazon.com/images/I/71u9sJmK36L._AC_UL800_QL65_.jpg",
  "Última Parada": "https://m.media-amazon.com/images/I/81i-R12Y7hL._AC_UL800_QL65_.jpg",
  "Eu Beijei Shara Wheeler": "https://m.media-amazon.com/images/I/81vR1L8T4NL._AC_UL800_QL65_.jpg",
  "Uma Farsa de Amor na Espanha": "https://m.media-amazon.com/images/I/71Y+z9fVzNL._AC_UL800_QL65_.jpg",
  "O Experimento de Amor em Nova York": "https://m.media-amazon.com/images/I/81i-R12Y7hL._AC_UL800_QL65_.jpg",
  "O Longo Jogo": "https://m.media-amazon.com/images/I/71C+l7Y9UPL._AC_UL800_QL65_.jpg",
  "Amor Corrompido": "https://m.media-amazon.com/images/I/81G3B5T4YhL._AC_UL800_QL65_.jpg",
  "Amor Proibido": "https://m.media-amazon.com/images/I/81Z3aR32F0L._AC_UL800_QL65_.jpg",
  "Amor Perigoso": "https://m.media-amazon.com/images/I/71Y+z9fVzNL._AC_UL800_QL65_.jpg",
  "Amor Mentiroso": "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UL800_QL65_.jpg",
  "Rei da Ira": "https://m.media-amazon.com/images/I/718y6CqQ9KL._AC_UL800_QL65_.jpg",
  "Perdida": "https://m.media-amazon.com/images/I/71zQYyM3WwL._AC_UL800_QL65_.jpg",
  "Encontrada": "https://m.media-amazon.com/images/I/71E3v1o8TCL._AC_UL800_QL65_.jpg",
  "Destinada": "https://m.media-amazon.com/images/I/71oO-9j4y2L._AC_UL800_QL65_.jpg",
  "Prometida": "https://m.media-amazon.com/images/I/71U8v0XW4XL._AC_UL800_QL65_.jpg",
  "Procura-se um Marido": "https://m.media-amazon.com/images/I/81xU-Ue9uXL._AC_UL800_QL65_.jpg",
  "No Mundo da Luna": "https://m.media-amazon.com/images/I/81Lg7Y9mU3L._AC_UL800_QL65_.jpg",
  "Para Sempre Seu": "https://m.media-amazon.com/images/I/718y6CqQ9KL._AC_UL800_QL65_.jpg",
  "O Que Resta de Mim": "https://m.media-amazon.com/images/I/81xU-Ue9uXL._AC_UL800_QL65_.jpg",
  "Apenas Amigos": "https://m.media-amazon.com/images/I/81r1j1NnZLL._AC_UL800_QL65_.jpg",
  "Simplesmente Amigos": "https://m.media-amazon.com/images/I/71G1mYk7SjL._AC_UL800_QL65_.jpg",
  "Teto Para Dois": "https://m.media-amazon.com/images/I/81k3f0e8fYL._AC_UL800_QL65_.jpg",
  "A Troca": "https://m.media-amazon.com/images/I/81B+G7x4KOL._AC_UL800_QL65_.jpg",
  "Na Estrada com o Ex": "https://m.media-amazon.com/images/I/81r52N2H9cL._AC_UL800_QL65_.jpg",
  "Para Todos os Garotos que Já Amei": "https://m.media-amazon.com/images/I/81s042Ff8hL._AC_UL800_QL65_.jpg",
  "P.S.: Ainda Amo Você": "https://m.media-amazon.com/images/I/81Ksc0-j7tL._AC_UL800_QL65_.jpg",
  "Agora e Para Sempre, Lara Jean": "https://m.media-amazon.com/images/I/81R56yH8JNL._AC_UL800_QL65_.jpg",
  "O Verão que Mudou Minha Vida": "https://m.media-amazon.com/images/I/81gL+l5q2NL._AC_UL800_QL65_.jpg",
  "O Príncipe Cruel": "https://m.media-amazon.com/images/I/81K09F+jP2L._AC_UL800_QL65_.jpg",
  "O Rei Perverso": "https://m.media-amazon.com/images/I/81Z3aR32F0L._AC_UL800_QL65_.jpg",
  "A Rainha do Nada": "https://m.media-amazon.com/images/I/81h2N3zVpYL._AC_UL800_QL65_.jpg",
  "Jogos Vorazes": "https://m.media-amazon.com/images/I/71u9sJmK36L._AC_UL800_QL65_.jpg",
  "Em Chamas": "https://m.media-amazon.com/images/I/71C+l7Y9UPL._AC_UL800_QL65_.jpg",
  "A Esperança": "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UL800_QL65_.jpg",
  "Métrica": "https://m.media-amazon.com/images/I/71Y+z9fVzNL._AC_UL800_QL65_.jpg",
  "Pausa": "https://m.media-amazon.com/images/I/81G3B5T4YhL._AC_UL800_QL65_.jpg",
  "Tarde Demais": "https://m.media-amazon.com/images/I/81i-R12Y7hL._AC_UL800_QL65_.jpg",
  "Odeio Te Amar": "https://m.media-amazon.com/images/I/71MUhPEx9-L._AC_UL800_QL65_.jpg",
  "Sob o Mesmo Teto": "https://m.media-amazon.com/images/I/81LTEfXYgcL._AC_UL800_QL65_.jpg",
  "Mil Vezes Amor": "https://m.media-amazon.com/images/I/71g-+Mn7zQL._AC_UL800_QL65_.jpg",
  "Acaso ou Destino": "https://m.media-amazon.com/images/I/71r+niNLzDL._AC_UL800_QL65_.jpg"
};
