export const bookCoversMap = {
  "Se Não Fosse Você": "https://m.media-amazon.com/images/I/91UJSr2IukL._AC_UL800_QL65_.jpg",
  "Amor por Acaso": "https://m.media-amazon.com/images/I/61t4VlpXoOL._AC_UL800_QL65_.jpg",
  "Sem Esperança": "https://m.media-amazon.com/images/I/91DszGVK+2L._AC_UL800_QL65_.jpg",
  "Talvez Agora": "https://m.media-amazon.com/images/I/81GH54cTScL._AC_UL800_QL65_.jpg",
  "Talvez Um Dia": "https://m.media-amazon.com/images/I/815OsC8zbwL._AC_UL800_QL65_.jpg",
  "Layla": "https://m.media-amazon.com/images/I/91-M+6ZOjuL._AC_UL800_QL65_.jpg",
  "Lembranças d'Ele": "https://m.media-amazon.com/images/I/81tvgUwzabL._AC_UL800_QL65_.jpg",
  "A Exceção à Regra": "https://m.media-amazon.com/images/I/71MUhPEx9-L._AC_UL800_QL65_.jpg",
  "Até o Verão Terminar": "https://m.media-amazon.com/images/I/81u8c5lziEL._AC_UL800_QL65_.jpg",
  "Confesse": "https://m.media-amazon.com/images/I/91JhEqiauUL._AC_UL800_QL65_.jpg",
  "É Assim que Acaba": "https://m.media-amazon.com/images/I/71sdFEHoRGL._AC_UL800_QL65_.jpg",
  "É Assim que Começa": "https://m.media-amazon.com/images/I/81Izv2GRWoL._AC_UL800_QL65_.jpg",
  "Novembro, 9": "https://m.media-amazon.com/images/I/917G-FdK2kL._AC_UL800_QL65_.jpg",
  "O Lado Feio do Amor": "https://m.media-amazon.com/images/I/81FEytag46L._AC_UL800_QL65_.jpg",
  "Todas as Suas (Im)Perfeições": "https://m.media-amazon.com/images/I/81tZj9h9PAL._AC_UL800_QL65_.jpg",
  "Uma Segunda Chance": "https://m.media-amazon.com/images/I/813WvRoZ0HL._AC_UL800_QL65_.jpg",
  "Verity": "https://m.media-amazon.com/images/I/91SDZ2eUj+L._AC_UL800_QL65_.jpg",
  "Apostando no Amor": "https://m.media-amazon.com/images/I/61qs2JCP4NL._AC_UL800_QL65_.jpg",
  "Melhor do que nos Filmes": "https://m.media-amazon.com/images/I/61y5iLUKS3L._AC_UL800_QL65_.jpg",
  "Mr. Wrong Number": "https://m.media-amazon.com/images/I/81tbn9DicaL._AC_UL800_QL65_.jpg",
  "Nada Como nos Filmes": "https://m.media-amazon.com/images/I/71E7CFZbWyL._AC_UL800_QL65_.jpg",
  "The Do-Over": "https://m.media-amazon.com/images/I/71g-+Mn7zQL._AC_UL800_QL65_.jpg",
  "The Love Wager": "https://m.media-amazon.com/images/I/71r+niNLzDL._AC_UL800_QL65_.jpg",
  "A Hipótese do Amor": "https://m.media-amazon.com/images/I/81LTEfXYgcL._AC_UL800_QL65_.jpg",
  "A Razão do Amor": "https://m.media-amazon.com/images/I/81bkmJnflPL._AC_UL800_QL65_.jpg",
  "A Teoria da Conquista": "https://m.media-amazon.com/images/I/71dFi0nYJFL._AC_UL800_QL65_.jpg",
  "Noiva": "https://m.media-amazon.com/images/I/812RDxFDd8L._AC_UL800_QL65_.jpg",
  "Not in Love": "https://m.media-amazon.com/images/I/71i-HM1ZrlL._AC_UL800_QL65_.jpg",
  "Xeque-Mate": "https://m.media-amazon.com/images/I/81O6eWVPaiL._AC_UL800_QL65_.jpg",
  "As Mil Partes do Meu Coração": "https://m.media-amazon.com/images/I/814pUv-EGbL._AC_UL800_QL65_.jpg",
  "Loucos por Livros": "https://covers.openlibrary.org/b/isbn/0593334833-L.jpg",
  "De Férias com Você": "https://covers.openlibrary.org/b/isbn/1984806750-L.jpg",
  "Leitura de Verão": "https://covers.openlibrary.org/b/isbn/1984806734-L.jpg",
  "Lugar Feliz": "https://books.google.com/books/content?id=2ByZEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Nem Te Conto": "https://books.google.com/books/content?id=jXKwEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Os Sete Maridos de Evelyn Hugo": "https://covers.openlibrary.org/b/isbn/1501156705-L.jpg",
  "Daisy Jones & The Six": "https://covers.openlibrary.org/b/isbn/1524798622-L.jpg",
  "Malibu Renasce": "https://books.google.com/books/content?id=lhfsDwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Carrie Soto Está de Volta": "https://books.google.com/books/content?id=mETaEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Em Outra Vida, Talvez?": "https://covers.openlibrary.org/b/isbn/1476712840-L.jpg",
  "Amor(es) Verdadeiro(s)": "https://covers.openlibrary.org/b/isbn/1476712832-L.jpg",
  "Corte de Espinhos e Rosas": "https://covers.openlibrary.org/b/isbn/1635575567-L.jpg",
  "Corte de Névoa e Fúria": "https://covers.openlibrary.org/b/isbn/1635575583-L.jpg",
  "Corte de Asas e Ruína": "https://covers.openlibrary.org/b/isbn/1635575591-L.jpg",
  "Corte de Chamas Prateadas": "https://covers.openlibrary.org/b/isbn/1635575613-L.jpg",
  "Casa de Terra e Sangue": "https://covers.openlibrary.org/b/isbn/1635574048-L.jpg",
  "Trono de Vidro": "https://covers.openlibrary.org/b/isbn/1619630346-L.jpg",
  "Quarta Asa": "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UL800_QL65_.jpg",
  "Chama de Ferro": "https://covers.openlibrary.org/b/isbn/1649374178-L.jpg",
  "A Última Carta": "https://books.google.com/books/content?id=QR-FEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Vermelho, Branco e Sangue Azul": "https://books.google.com/books/content?id=OhqEDwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Última Parada": "https://covers.openlibrary.org/b/isbn/1250244625-L.jpg",
  "Eu Beijei Shara Wheeler": "https://covers.openlibrary.org/b/isbn/1250244633-L.jpg",
  "Uma Farsa de Amor na Espanha": "https://books.google.com/books/content?id=aNgJEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "O Experimento de Amor em Nova York": "https://books.google.com/books/content?id=s3c3EAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "O Longo Jogo": "https://covers.openlibrary.org/b/isbn/1668007436-L.jpg",
  "Amor Corrompido": "https://books.google.com/books/content?id=7k5KEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Amor Proibido": "https://covers.openlibrary.org/b/isbn/1728274273-L.jpg",
  "Amor Perigoso": "https://books.google.com/books/content?id=D11TEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Amor Mentiroso": "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UL800_QL65_.jpg",
  "Rei da Ira": "https://books.google.com/books/content?id=7YZTEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Perdida": "https://covers.openlibrary.org/b/olid/OL26335580M-L.jpg",
  "Encontrada": "https://covers.openlibrary.org/b/olid/OL28306880M-L.jpg",
  "Destinada": "https://covers.openlibrary.org/b/olid/OL28822540M-L.jpg",
  "Prometida": "https://covers.openlibrary.org/b/olid/OL33131300M-L.jpg",
  "Procura-se um Marido": "https://covers.openlibrary.org/b/olid/OL26292610M-L.jpg",
  "No Mundo da Luna": "https://books.google.com/books/content?id=01b_DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Para Sempre Seu": "https://books.google.com/books/content?id=6Ek5EAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "O Que Resta de Mim": "https://books.google.com/books/content?id=t8CQEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Apenas Amigos": "https://books.google.com/books/content?id=sTifDwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Simplesmente Amigos": "https://books.google.com/books/content?id=NKWJEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Teto Para Dois": "https://books.google.com/books/content?id=N2CGEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "A Troca": "https://books.google.com/books/content?id=d_G7DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Na Estrada com o Ex": "https://books.google.com/books/content?id=wFr_DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Para Todos os Garotos que Já Amei": "https://books.google.com/books/content?id=GpSPEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "P.S.: Ainda Amo Você": "https://books.google.com/books/content?id=m9SVEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Agora e Para Sempre, Lara Jean": "https://books.google.com/books/content?id=M9SVEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "O Verão que Mudou Minha Vida": "https://covers.openlibrary.org/b/isbn/1416968288-L.jpg",
  "O Príncipe Cruel": "https://books.google.com/books/content?id=K9k6DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "O Rei Perverso": "https://books.google.com/books/content?id=L9k6DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "A Rainha do Nada": "https://books.google.com/books/content?id=M9k6DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Jogos Vorazes": "https://covers.openlibrary.org/b/isbn/0439023521-L.jpg",
  "Em Chamas": "https://covers.openlibrary.org/b/isbn/0439023491-L.jpg",
  "A Esperança": "https://covers.openlibrary.org/b/isbn/0439023513-L.jpg",
  "Métrica": "https://books.google.com/books/content?id=a6tBngEACAAJ&printsec=frontcover&img=1&zoom=0",
  "Pausa": "https://books.google.com/books/content?id=u-q2mgEACAAJ&printsec=frontcover&img=1&zoom=0",
  "Tarde Demais": "https://books.google.com/books/content?id=qY4MEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Odeio Te Amar": "https://books.google.com/books/content?id=fFd_EAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Sob o Mesmo Teto": "https://books.google.com/books/content?id=CVSWEAAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Mil Vezes Amor": "https://books.google.com/books/content?id=ZWL0DwAAQBAJ&printsec=frontcover&img=1&zoom=0",
  "Acaso ou Destino": "https://books.google.com/books/content?id=yYxlEAAAQBAJ&printsec=frontcover&img=1&zoom=0"
};
